Use MushVsGrump;
GO
IF OBJECT_ID('dbo.Inventory', 'U') IS NOT NULL 
	DROP TABLE Inventory;
CREATE TABLE Inventory(
	ItID int,
	PRIMARY KEY(ItID),
	CONSTRAINT Inv_to_Item FOREIGN KEY (ItID) REFERENCES
		Item (ItID) ON DELETE CASCADE ON UPDATE CASCADE
	)